### ISSUE TITLE
support cata pls

### ISSUE THREAD

**Issue by Megumin230** [thehallowedfire/ModernCharacterFrame#13]
the game's own cataclysm character ui is trash rn, pls bring support of this addon again, to cata

**Comment by Megumin230** [comment]
This addon is the perfect character ui, pls bring it to cataclysm

**Comment by thehallowedfire** [comment]
@Megumin230 I can't port it to Cata because Cata Classic now has all those functions by default. But I have made Improved Character Frame addon (https://github.com/thehallowedfire/ImprovedCharacterFrame) which adds some of functionality from Modern Character Frame and fixes some Blizzard's bugs as well. Not sure if I'm gonna support it very actively, but it works for now and serves my purposes. Feel free to try and if you'll find any issues - report them in new repository.
